version: '3.4'

services:
  postgres:
    build: docker/db/
    environment:
      - POSTGRES_DB=odc
      - POSTGRES_PASSWORD=odcpass
      - POSTGRES_USER=odcuser
    ports:
      - "5432:5432"
    restart: always
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      SERVICES: sqs, s3
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
      QUEUE_NAME: my-queue
      BUCKET_NAME: my-bucket
      AWS_DEFAULT_REGION: ap-southeast-2
    volumes:
      - "./docker/localstack.sh:/docker-entrypoint-initaws.d/localstack.sh"
      - "./docker/localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"  # https://docs.localstack.cloud/references/init-hooks/
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  fmc:
    build:
      context: .
    working_dir: /app
    links:
      - postgres:postgres
      - localstack:localstack
    ports:
      - "8787:8787"  # dask UI
    environment:
      DB_PORT: 5432
      DB_HOSTNAME: postgres
      DB_USERNAME: odcuser
      DB_PASSWORD: odcpass
      DB_DATABASE: odc
      GDAL_HTTP_MAX_RETRY: 5
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_ENDPOINT_URL: http://localstack:4566
      QUEUE_NAME: my-queue
      BUCKET_NAME: my-bucket
      MODEL_PATH: /app/rf_fmc.pickle
      QUEUE_URL: http://localstack:4566/000000000000/my-queue
    depends_on:
      - postgres
      - localstack
    restart: always
    command: tail -f /dev/null

#    volumes:
#      - ./:/app

volumes:
  sqs: null
