version: '3.4'

services:
  postgres:
    # db with some data from ls5, 7, 8 pre-indexed
    build: docker/db/
    environment:
      - POSTGRES_DB=odc
      - POSTGRES_PASSWORD=odcpass
      - POSTGRES_USER=odcuser
    ports:
      - "5432:5432"
    restart: always
  fmc:
    build:
      context: .
    links:
      - postgres:postgres
    environment:
      DB_PORT: 5432
      DB_HOSTNAME: postgres
      DB_USERNAME: odcuser
      DB_PASSWORD: odcpass
      DB_DATABASE: odc
      AWS_NO_SIGN_REQUEST: "yes"
      GDAL_HTTP_MAX_RETRY: 5
    depends_on:
      - postgres
    restart: always
    command: tail -f /dev/null