version: '3.4'

services:
  postgres:
    # clean postgis db
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=odc
      - POSTGRES_PASSWORD=odcpass
      - POSTGRES_USER=odcuser
    ports:
      - "5432:5432"
    restart: always