output_folder: s3://dea-public-data-dev/projects/burn_cube/derivative

input_products:
  platform: s2
  input_bands:
    - nbart_blue
    - nbart_green
    - nbart_red
    - nbart_red_edge_1
    - nbart_red_edge_2
    - nbart_red_edge_3
    - nbart_nir_1
    - nbart_nir_2
    - nbart_swir_2
    - nbart_swir_3
    - oa_fmask

product:
  name: ga_s2ab_nbart_dea_fmc
  short_name: ga_s2ab_nbart_dea_fmc
  version: 3.0.0
  product_family: fmc
  bands:
    - count
  inherit_skip_properties:
    - eo:cloud_cover
    - fmask:clear
    - fmask:snow
    - fmask:cloud
    - fmask:water
    - fmask:cloud_shadow
    - eo:sun_elevation
    - eo:sun_azimuth
    - gqa:iterative_stddev_x
    - gqa:iterative_stddev_y
    - gqa:iterative_stddev_xy
    - gqa:stddev_xy
    - gqa:stddev_x
    - gqa:stddev_y
    - gqa:mean_xy
    - gqa:mean_x
    - gqa:mean_y
    - gqa:abs_xy
    - gqa:abs_x
    - gqa:abs_y
    - gqa:abs_iterative_mean_y
    - gqa:abs_iterative_mean_x
    - gqa:abs_iterative_mean_xy
    - gqa:iterative_mean_xy
    - gqa:iterative_mean_x
    - gqa:iterative_mean_y
    - gqa:cep90
    - landsat:landsat_product_id
    - landsat:landsat_scene_id
    - landsat:collection_category
    - landsat:collection_number
    - landsat:wrs_path
    - landsat:wrs_row
    - fmask:clear

model_path: https://dea-public-data-dev.s3.ap-southeast-2.amazonaws.com/projects/burn_cube/configs/RF_AllBands_noLC_DEA_labeless.joblib
